<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "mb_teasers"
 *
 * Auto generated by Extension Builder 2021-01-03
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Mb Teasers',
    'description' => 'This extension contains teasers.',
    'category' => 'plugin',
    'author' => 'Muhammad Zohaib',
    'author_email' => 'muhammad.zohaib@kreativrudel.de',
    'state' => 'alpha',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '11.3.0-11.3.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
